name: Akilli Dis Ticaret Botunu Calistir

on:
  workflow_dispatch: # Bu satır internet arayüzüne "Buton" ekler

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Kutuphaneleri Yukle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Botu Tetikle
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: python main.py
